// Re-export all schemas
export {
  ProjectStructureSchema,
  MarketingSiteSchema,
  AuthProviderSchema,
  AnalyticsProviderSchema,
  UploadsProviderSchema,
  PaymentProviderSchema,
  // shadcn v4 schemas
  ComponentLibrarySchema,
  ShadcnStyleSchema,
  BaseColorSchema,
  ThemeColorSchema,
  IconLibrarySchema,
  FontSchema,
  MenuAccentSchema,
  MenuColorSchema,
  RadiusSchema,
  // Config schemas
  PackageManagerSchema,
  AddonSchema,
  DesignSystemConfigSchema,
  AuthConfigSchema,
  IntegrationsConfigSchema,
  ProjectConfigSchema,
  CLIInputSchema,
  DEFAULT_CONFIG,
} from './schemas.js'

// Re-export all types
export type {
  ProjectStructure,
  MarketingSite,
  AuthProvider,
  AnalyticsProvider,
  UploadsProvider,
  PaymentProvider,
  // shadcn v4 types
  ComponentLibrary,
  ShadcnStyle,
  BaseColor,
  ThemeColor,
  IconLibrary,
  Font,
  MenuAccent,
  MenuColor,
  Radius,
  // Config types
  PackageManager,
  Addon,
  DesignSystemConfig,
  AuthConfig,
  IntegrationsConfig,
  ProjectConfig,
  CLIInput,
  VirtualFile,
  VirtualDirectory,
  VirtualNode,
  VirtualFileTree,
  GeneratorOptions,
  GeneratorResult,
} from './types.js'
