// Re-export all schemas
export {
  ProjectStructureSchema,
  MarketingSiteSchema,
  AuthProviderSchema,
  AnalyticsProviderSchema,
  UploadsProviderSchema,
  BaseColorSchema,
  ThemeColorSchema,
  MenuAccentSchema,
  IconLibrarySchema,
  FontFamilySchema,
  BorderRadiusSchema,
  SpacingScaleSchema,
  PackageManagerSchema,
  AddonSchema,
  DesignSystemConfigSchema,
  AuthConfigSchema,
  IntegrationsConfigSchema,
  ProjectConfigSchema,
  CLIInputSchema,
  DEFAULT_CONFIG,
} from './schemas.js'

// Re-export all types
export type {
  ProjectStructure,
  MarketingSite,
  AuthProvider,
  AnalyticsProvider,
  UploadsProvider,
  BaseColor,
  ThemeColor,
  MenuAccent,
  IconLibrary,
  FontFamily,
  BorderRadius,
  SpacingScale,
  PackageManager,
  Addon,
  DesignSystemConfig,
  AuthConfig,
  IntegrationsConfig,
  ProjectConfig,
  CLIInput,
  VirtualFile,
  VirtualDirectory,
  VirtualNode,
  VirtualFileTree,
  GeneratorOptions,
  GeneratorResult,
} from './types.js'
